# Generated by Django 6.0.5 on 2026-05-25 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Export'), ('UTILITY', 'Utility Portal'), ('TRAVEL', 'Corporate Travel API')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_file_reference', models.CharField(blank=True, max_length=500, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.company')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 (Direct)'), ('SCOPE_2', 'Scope 2 (Indirect - Electricity)'), ('SCOPE_3', 'Scope 3 (Value Chain / Travel)')], max_length=20)),
                ('raw_quantity', models.FloatField()),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_quantity', models.FloatField(help_text='Converted to standard unit (e.g., kgCO2e or kWh)')),
                ('normalized_unit', models.CharField(default='kgCO2e', max_length=50)),
                ('date_of_activity', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved for Audit'), ('REJECTED', 'Rejected / Suspicious')], default='PENDING', max_length=20)),
                ('audit_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.company')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.datasource')),
            ],
        ),
    ]
